spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cdcdemo}
    username: ${SPRING_DATASOURCE_USERNAME:cdcuser}
    password: ${SPRING_DATASOURCE_PASSWORD:cdcpassword}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/cdcaudit}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

debezium:
  db:
    host: ${DEBEZIUM_DB_HOST:localhost}
    port: ${DEBEZIUM_DB_PORT:5432}
    name: ${DEBEZIUM_DB_NAME:cdcdemo}
    user: ${DEBEZIUM_DB_USER:cdcuser}
    password: ${DEBEZIUM_DB_PASSWORD:cdcpassword}

server:
  port: 8080

logging:
  level:
    com.cdcdemo: INFO
    io.debezium: WARN
